### ISSUE TITLE
Any frontend UI without needing to login?

### ISSUE THREAD

**Issue by bilogic** [199ocero/filachat#14]
### What happened?

I can't open a question, so writing here instead

### How to reproduce the bug

N/A

### Package Version

0.2.0-alpha.5

### PHP Version

8.2

### Laravel Version

10

**Comment by 199ocero** [comment]
This is is specific to filament authenticated users

**Comment by maukoese** [comment]
I can contribute to make this possible. I need to output a floating chat widget, with a preselected user/agent, so I think I can help build that logic.

In my scenario, this widget will be loaded in a mobile app as well as on a website, and the selected user will receive all the conversations that show up.

**Comment by bilogic** [comment]
wonderful that's exactly what I was asking for!
