### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by blindmelon07** [199ocero/filachat#8]
### What happened?

Method Filament\Forms\Components\FileUpload::fetchFile Information does not exist. 
 when i access admin/filachat

### How to reproduce the bug

Method Filament\Forms\Components\FileUpload::fetchFile Information does not exist.

### Package Version

3

### PHP Version

8.2

### Laravel Version

11

### Which operating systems does with happen with?

Windows

### Notes

please help me

**Comment by 199ocero** [comment]
Hello @blindmelon07 did you use the latest filament?

**Comment by blindmelon07** [comment]
Yes sir I used the latest 3.2

**Comment by blindmelon07** [comment]
And I used fila starter kit for filament

**Comment by 199ocero** [comment]
There seems to be an issue with filament startkit. There are devs already using it and `fetchFileInformation()` method is found in the docs: https://filamentphp.com/docs/3.x/forms/fields/file-upload#prevent-file-information-fetching
